name: Sync Rules

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
  
jobs:
  Sync-Rules:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install Dependencies
      run: |
        npm ci
        
    - name: Run Sync Script
      run: npm run sync
      env:
        TZ: 'Asia/Shanghai'
        NODE_OPTIONS: '--experimental-specifier-resolution=node'
        
    - name: Commit Changes
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "rin.tohsaka@fate-stay-night.com"
          git config --local user.name "Rin Tohsaka"
          git add .
          git commit -m "✨ Auto Update by Rin $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push
        fi

    - name: Cleanup Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

    - name: Trigger Deploy Workflow  
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: trigger-deploy