name: Sync Rules

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"
  
jobs:
  Sync-Rules:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Dependencies
      run: |
        npm install typescript ts-node @types/node
        
    - name: Run Sync Script
      run: npx ts-node Chores/scripts/main.ts
      env:
        TZ: 'Asia/Shanghai'
        
    - name: Commit Changes
      run: |
        if [[ -n $(git status -s) ]]; then
          git config --local user.email "rin.tohsaka@fate-stay-night.com"
          git config --local user.name "Rin Tohsaka"
          git add .
          git commit -m "✨ Auto Update by Rin $(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M')"
          git push
        fi

    - name: Cleanup Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 2

    - name: Trigger Deploy Workflow  
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        event-type: trigger-deploy